## Notes

## qualtRics reading with convert = TRUE makes factors
## These factors have levels
## Levels have to be sequential
## Hence it will mess up coding where the Qualtrics coding was not sequential
## like
# o	Diplôme universitaire de premier cycle  (8)
# o	Diplôme universitaire de 2e ou 3e cycle  (9)
# o	Ne sais pas  (12)
## The last will be treated as 10, not 12...
## This is dangerous, as the English survey has
## I don't know as 12.

# label Logical. TRUE to export survey responses as Choice Text or FALSE to export
# survey responses as values

# convert Logical. If TRUE, then the fetch_survey function will convert certain question
# types (e.g. multiple choice) to proper data type in R. Defaults to TRUE.

# save_dir String. Directory where survey results will be stored. Defaults to a temporary
# directory which is cleaned when your R session is terminated. This argument
# is useful if you’d like to store survey r

# breakout_sets Logical. If TRUE, then the fetch_survey function will split multiple choice
# question answers into columns. If FALSE, each multiple choice question is one
# column. Defaults to TRUE.

library(qualtRics)

surveys <- all_surveys()

not_working <- c(
  "gfhs-1_survey_t5_parent-1",
  "gfhs-1_survey_t6_parent-2",
  "gfhs-1_survey_t6_parent-1",
  "gfhs-3_survey_t2_parent-1",
  "gfhs-3_survey_t1_parent-1",
  "gfhs-123_covid-survey_parent-1",
  "gfhs-2_survey_t3_parent-1",
  "QSupport_1Y - Pilot2 - P1 - Copy"
)
surveys <- surveys %>%
  filter(name %in% not_working)

all_surveys <- surveys %>%
  mutate(
    data = map(
      id,
      ~ fetch_survey(
        surveyID = .x,
        verbose = TRUE,
        col_types = cols(.default = "c")
      )
   )
  )

bad_surveys <- all_surveys() %>% filter(name %in% not_working)
bad_surveys %>% pull(id) %>% clipr::write_clip()

SV_2rF0CcmMF1MmTiJ
SV_4PGTagXUNqyDk2N
SV_54O8af3hH9BMSsB
SV_bkkJJnx32TF1SSh
SV_bQ1k3sEqxrXN71P
SV_eysW99OTsMo7Xdb
SV_ezFnmDF8xXheiR7
SV_9WZiybBGCu3ESyx

surveys
before_bad <- which(surveys$id == "SV_esKOor4nezsAVZb")
surveys %>% slice(before_bad + 1) %>% pull(name)

fetch_survey(id$id)


##########
ml <- all_mailinglists()

cm <- extract_colmap(mysurvey2)

cm$description
id = surveys$id[10]

#cm %>% filter(qname == "1_Q42_11") %>% pull(description)
q <- survey_questions(id)
#View(q)
#q %>% filter(qname == "Q42") %>% pull(question)


des <- qualtRics::qualtRicsConfigFile(id)
des$
ddes$metadata
# read_survey
# Reads comma separated CSV files generated by Qualtrics software. The second line containing the
# variable labels is imported. Repetitive introductions to matrix questions are automatically removed.
# Variable labels are stored as attributes

